### ISSUE TITLE
Error in windows when `sui-bundler dev`

### ISSUE THREAD

**Issue by juanmaguitar** [SUI-Components/sui#433]
### Package

"@s-ui/bundler": "^3.29.0",

### Description

Fatal Error in Windows

### Steps to Reproduce

Install packages
```
"@s-ui/bundler": "^3.29.0",
"@s-ui/component-peer-dependencies": "^1.5.0"
```

create proper structure

`app.js`
```
import React from 'react'
import ReactDOM from 'react-dom'

ReactDOM.render(<h1>Hola Mundo</h1>, document.getElementById('⚛️'))
```

`index.html`
```
<div id="⚛️"></div>
```
 
**Expected behavior:** [What you expect to happen]

Bundle and execute local server 

**Actual behavior:** [What actually happens]

```
λ yarn start
yarn run v1.10.1
$ sui-bundler dev
C:\Users\almui\bootcamp\collab\schibsted-sui-tools-training\staff\almu-itur\sui-bundler-demo\node_modules\@s-ui\bundler\webpack.config.dev.js:56
       exclude: new RegExp(
                ^

SyntaxError: Invalid regular expression: /node_modules(?!\@s-ui\(svg|studio)(\workbench)?\src)/: Unmatched ')'
   at new RegExp (<anonymous>)
   at Object.<anonymous> (C:\Users\almui\bootcamp\collab\schibsted-sui-tools-training\staff\almu-itur\sui-bundler-demo\node_modules\@s-ui\bundler\webpack.config.dev.js:56:18)
   at Module._compile (module.js:653:30)
   at Object.Module._extensions..js (module.js:664:10)
   at Module.load (module.js:566:32)
   at tryModuleLoad (module.js:506:12)
   at Function.Module._load (module.js:498:3)
   at Module.require (module.js:597:17)
   at require (internal/module.js:11:18)
   at Object.<anonymous> (C:\Users\almui\bootcamp\collab\schibsted-sui-tools-training\staff\almu-itur\sui-bundler-demo\node_modules\@s-ui\bundler\bin\sui-bundler-dev.js:20:23)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Additional Information

Windows Machine

**Comment by carlosvillu** [comment]
Relative issue: https://github.com/GoogleChromeLabs/squoosh/issues/282

**Comment by nucliweb** [comment]
The problem is that in Windows with `\(` we escape the character `(` of the block `(svg|studio)`

[Windows Regular Expression Syntax Reference](https://docs.microsoft.com/en-us/windows/desktop/tablet/regular-expression-syntax-reference#escaping-characters) 

We have to options to solve it.

*Option 1*
```
        exclude: new RegExp(
          `node_modules(?!${path.sep}@s-ui${path.sep}${path.sep}(svg|studio)(${
            path.sep
          }workbench)?${path.sep}src)`
        )
```

*Option 2*
```
        exclude: new RegExp(
          `node_modules(?!${path.sep}@s-ui(${path.sep}svg|${path.sep}studio)(${
            path.sep
          }workbench)?${path.sep}src)`
        )
```

I prefer the second option, so I will send a PR with this solution 😊

**Comment by midudev** [comment]
Option 2 preferred for me.
